name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        make install
    - name: Run application
      run: |
        make run &
        sleep 10
    - name: Test application
      run: |
        curl -X POST -d "query=machine learning" http://localhost:3000/search
